# ============================================================
# AI Office v1.4 Documentation and Git Checkpoint Installer
# FIXED
# ============================================================
$ErrorActionPreference = "Stop"
$Repository = "E:\AI\AI-Office"

if (-not (Test-Path -LiteralPath $Repository -PathType Container)) {
    throw "AI Office repository not found at $Repository"
}

Set-Location $Repository

$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$BackupDirectory = Join-Path $Repository ("workspace\documentation-backups\" + $Timestamp)
New-Item -ItemType Directory -Path $BackupDirectory -Force | Out-Null

function Write-Base64File {
    param(
        [Parameter(Mandatory=$true)][string]$RelativePath,
        [Parameter(Mandatory=$true)][string]$Base64Content
    )

    $Destination = Join-Path $Repository $RelativePath
    $Parent = Split-Path -Parent $Destination

    if ($Parent -and -not (Test-Path -LiteralPath $Parent -PathType Container)) {
        New-Item -ItemType Directory -Path $Parent -Force | Out-Null
    }

    if (Test-Path -LiteralPath $Destination -PathType Leaf) {
        $BackupPath = Join-Path $BackupDirectory $RelativePath
        $BackupParent = Split-Path -Parent $BackupPath

        if ($BackupParent -and -not (Test-Path -LiteralPath $BackupParent -PathType Container)) {
            New-Item -ItemType Directory -Path $BackupParent -Force | Out-Null
        }

        Copy-Item -LiteralPath $Destination -Destination $BackupPath -Force
        Write-Host "[BACKUP ] $RelativePath" -ForegroundColor Yellow
    }

    $Bytes = [Convert]::FromBase64String($Base64Content)
    [IO.File]::WriteAllBytes($Destination, $Bytes)
    Write-Host "[WRITTEN] $RelativePath" -ForegroundColor Green
}

Write-Base64File -RelativePath "README.md" -Base64Content "IyBBSSBPZmZpY2UKCkFJIE9mZmljZSBpcyBhIG1vZHVsYXIsIGxvY2FsLWZpcnN0IGF1dG9ub21vdXMgZW50ZXJwcmlzZSBvcGVyYXRpbmcgc3lzdGVtIHBvd2VyZWQgYnkgT3BlbkNsYXcuCgpJdCBjb29yZGluYXRlcyBleGVjdXRpdmUgcGxhbm5pbmcsIGRlcGFydG1lbnQgd29yaywgbG9uZy10ZXJtIG1lbW9yeSwgYXV0b25vbW91cyB3b3JrZmxvd3MsIGh1bWFuIGFwcHJvdmFscywgYmFja2dyb3VuZCB3b3JrZXJzLCBsaXZlIGV4ZWN1dGlvbiwgYW5kIG9wZXJhdGlvbmFsIHJlcG9ydGluZyBmcm9tIGEgc2luZ2xlIGV4dGVuc2libGUgcGxhdGZvcm0uCgojIyBDdXJyZW50IFN0YXR1cwoKfCBGaWVsZCB8IEN1cnJlbnQgdmFsdWUgfAp8LS0tfC0tLXwKfCBDdXJyZW50IHBoYXNlIHwgUHJlcGFyaW5nIEtub3dsZWRnZSBHcmFwaCBhbmQgUmVhc29uaW5nIHwKfCBDdXJyZW50IG1pbGVzdG9uZSB8IENvcmUgQUkgT2ZmaWNlIFBsYXRmb3JtIENlcnRpZmllZCB8CnwgVmVyc2lvbiB8IDEuNC4wIHwKfCBSZWxlYXNlIHN0YXR1cyB8IE9wZXJhdGlvbmFsIHwKfCBOZXh0IHJlbGVhc2UgfCB2MS41IEtub3dsZWRnZSBHcmFwaCBhbmQgUmVhc29uaW5nIHwKCiMjIE9wZXJhdGlvbmFsIENhcGFiaWxpdGllcwoKLSBFeGVjdXRpdmUgQ2hpZWYgb2YgU3RhZmYKLSBEZXBhcnRtZW50IGFyY2hpdGVjdHVyZSBhbmQgZGVsZWdhdGlvbgotIEludGVyLWRlcGFydG1lbnQgTWVzc2FnZSBCdXMKLSBRdWV1ZSBlbmdpbmUgYW5kIHJvdXRpbmcKLSBDZXJ0aWZpZWQgT3BlbkNsYXcgYnJpZGdlCi0gQXV0aGVudGljYXRlZCBsaXZlIGV4ZWN1dGlvbgotIFJlc3VsdCBub3JtYWxpemF0aW9uIGFuZCBhcnRpZmFjdCBwdWJsaXNoaW5nCi0gTG9uZy10ZXJtIG1lbW9yeQotIE1lbW9yeSBzZWFyY2gsIHJlY2FsbCwgY29udGV4dCBwYWNrZXRzLCBoZWFsdGgsIGFuZCBmZWVkYmFjawotIEF1dG9ub21vdXMgd29ya2Zsb3cgZ29hbHMsIHBsYW5zLCBhbmQgcGVyc2lzdGVudCBydW5zCi0gSHVtYW4gYXBwcm92YWwgZ2F0ZXMKLSBSZXRyeSwgY2hlY2twb2ludCwgZmFpbHVyZSwgYW5kIHJlc3RhcnQgcmVjb3ZlcnkKLSBCYWNrZ3JvdW5kIHdvcmtlciBjeWNsZXMKLSBNb25pdG9yaW5nIGFuZCBleGVjdXRpdmUgcmVwb3J0aW5nCi0gTG9jYWwgQUkgT2ZmaWNlIGRhc2hib2FyZAotIEdhdGV3YXkgdG9rZW4gcm90YXRpb24gdXRpbGl0eQoKIyMgUm9hZG1hcAoKQ29tcGxldGVkOgoKLSB2MS4xIE9wZW5DbGF3IEJyaWRnZQotIHYxLjIgRGVwYXJ0bWVudCBJbnRlbGxpZ2VuY2UKLSB2MS4zIExvbmctVGVybSBNZW1vcnkKLSB2MS40IEF1dG9ub21vdXMgV29ya2Zsb3dzCgpQbGFubmVkOgoKLSB2MS41IEtub3dsZWRnZSBHcmFwaCBhbmQgUmVhc29uaW5nCi0gdjEuNiBNdWx0aS1BZ2VudCBDb2xsYWJvcmF0aW9uCi0gdjEuNyBQZXJzb25hbCBGaW5hbmNpYWwgT2ZmaWNlCi0gdjEuOCBCdXNpbmVzcyBJbmN1YmF0b3IKLSB2Mi4wIEF1dG9ub21vdXMgQUkgRW50ZXJwcmlzZQotIFBvc3QtdjIuMCBTZWxmLUhvc3RpbmcgQUkgT2ZmaWNlCgpEaXNjb3JkIGludGVncmF0aW9uIGlzIHBsYW5uZWQgYXMgYSBtb2JpbGUgY29tbWFuZCBhbmQgYXBwcm92YWwgY2hhbm5lbC4KClNlZSBbUk9BRE1BUC5tZF0oUk9BRE1BUC5tZCksIFtWSVNJT04ubWRdKFZJU0lPTi5tZCksIGFuZCBbUFJPSkVDVC1TVEFUVVMubWRdKFBST0pFQ1QtU1RBVFVTLm1kKS4KCiMjIERhc2hib2FyZAoKYGBgcG93ZXJzaGVsbApTZXQtTG9jYXRpb24gIkU6XEFJXEFJLU9mZmljZSIKCnBvd2Vyc2hlbGwgLUV4ZWN1dGlvblBvbGljeSBCeXBhc3MgLUZpbGUgYAogICAgIi5cc2NyaXB0c1xkYXNoYm9hcmRcU3RhcnQtQUlPZmZpY2VEYXNoYm9hcmQucHMxIiBgCiAgICAtT3BlbkJyb3dzZXIKYGBgCgpEZWZhdWx0IGFkZHJlc3M6CgpgYGB0ZXh0Cmh0dHA6Ly8xMjcuMC4wLjE6MTg4ODAvCmBgYAoKIyMgUmVwb3NpdG9yeSBSdWxlCgpTZWNyZXRzIGFuZCBsaXZlIHRva2VucyBtdXN0IG5vdCBiZSBjb21taXR0ZWQuCg=="
Write-Base64File -RelativePath "VISION.md" -Base64Content "IyBBSSBPZmZpY2UgVmlzaW9uCgojIyBQdXJwb3NlCgpBSSBPZmZpY2UgZXhpc3RzIHRvIHJlZHVjZSB0aGUgbWVudGFsIGxvYWQgb2YgbWFuYWdpbmcgd29yaywgZmluYW5jZXMsIHNpZGUgaW5jb21lLCBjcmVhdGl2ZSBwcm9qZWN0cywgZnV0dXJlIGJ1c2luZXNzZXMsIGFuZCBwZXJzb25hbCBhZG1pbmlzdHJhdGlvbi4KCkl0IHNob3VsZCBmdW5jdGlvbiBhcyBhIGRlcGVuZGFibGUgbG9jYWwgZXhlY3V0aXZlIG9yZ2FuaXphdGlvbiByYXRoZXIgdGhhbiBhIGNvbGxlY3Rpb24gb2YgZGlzY29ubmVjdGVkIGNoYXRib3RzLgoKIyMgTm9ydGggU3RhcgoKQSBjb21wbGV0ZWQgQUkgT2ZmaWNlIGNhbiByZWNlaXZlIGEgZ29hbCBmcm9tIGEgcGhvbmUgb3IgY29tcHV0ZXIsIHVuZGVyc3RhbmQgdGhlIHJlbGV2YW50IHBlb3BsZSBhbmQgcHJvamVjdHMsIHJlY2FsbCBwcmlvciBkZWNpc2lvbnMsIGNyZWF0ZSBhIHBsYW4sIGRlbGVnYXRlIHdvcmssIGV4ZWN1dGUgYXBwcm92ZWQgYWN0aW9ucywgbW9uaXRvciBwcm9ncmVzcywgcmVjb3ZlciBmcm9tIGludGVycnVwdGlvbnMsIHJlcXVlc3QgaHVtYW4gYXBwcm92YWwgd2hlbiBuZWVkZWQsIGFuZCByZXBvcnQgdGhlIHJlc3VsdCB0aHJvdWdoIG9uZSBjb250cm9sIGNlbnRlci4KCiMjIENvcmUgUHJpbmNpcGxlcwoKLSBMb2NhbC1maXJzdCBvcGVyYXRpb24KLSBIdW1hbi1zdXBlcnZpc2VkIGF1dG9ub215Ci0gTWVtb3J5IHdpdGggcHJvdmVuYW5jZQotIE1vZHVsYXIgZGVwYXJ0bWVudHMKLSBSZWNvdmVyYWJsZSBleGVjdXRpb24KLSBPYnNlcnZhYmxlIG9wZXJhdGlvbnMKLSBTZWN1cml0eSBieSBkZXNpZ24KLSBQcmFjdGljYWwgdmFsdWUgZmlyc3QKCiMjIExvbmctVGVybSBPdXRjb21lCgpBSSBPZmZpY2UgYmVjb21lcyBhbiBhdXRvbm9tb3VzIEFJIGVudGVycHJpc2UgdGhhdCBjb29yZGluYXRlcyBwcm9mZXNzaW9uYWwgd29yaywgcGVyc29uYWwgYWRtaW5pc3RyYXRpb24sIGZpbmFuY2lhbCBwbGFubmluZywgc2lkZSBodXN0bGVzLCBhbmQgbmV3IHZlbnR1cmVzIHVuZGVyIG9uZSBleGVjdXRpdmUgb3BlcmF0aW5nIG1vZGVsLgoKQWZ0ZXIgdjIuMCwgdGhlIHN5c3RlbSBzaG91bGQgYmVjb21lIHNlbGYtaG9zdGluZzogYWJsZSB0byBkZXNpZ24sIGdlbmVyYXRlLCB2YWxpZGF0ZSwgdGVzdCwgcGFja2FnZSwgaW5zdGFsbCwgZG9jdW1lbnQsIG1vbml0b3IsIGFuZCByb2xsIGJhY2sgaXRzIG93biB1cGdyYWRlcyB1bmRlciBodW1hbiBzdXBlcnZpc2lvbi4K"
Write-Base64File -RelativePath "ROADMAP.md" -Base64Content "IyBBSSBPZmZpY2UgUm9hZG1hcAoKIyMgQ29tcGxldGVkCgojIyMgdjEuMSDigJQgT3BlbkNsYXcgQnJpZGdlCkF1dGhlbnRpY2F0ZWQgYnJpZGdlLCBsaXZlIGV4ZWN1dGlvbiwgcmVzdWx0IHByb2Nlc3NpbmcsIGFydGlmYWN0cywgYW5kIGNlcnRpZmljYXRpb24uCgojIyMgdjEuMiDigJQgRGVwYXJ0bWVudCBJbnRlbGxpZ2VuY2UKRGVwYXJ0bWVudCBpZGVudGl0aWVzLCByb3V0aW5nLCBrbm93bGVkZ2UsIGxlYXJuaW5nLCByZXVzYWJsZSBsZXNzb25zLCBhbmQgcmVwb3J0aW5nLgoKIyMjIHYxLjMg4oCUIExvbmctVGVybSBNZW1vcnkKTWVtb3J5IHNjb3BlcywgY2FwdHVyZSwgc2VhcmNoLCByZWNhbGwsIGNvbnRleHQgcGFja2V0cywgY29uZmlkZW5jZSwgZmVlZGJhY2ssIGhlYWx0aCwgYW5kIGNvbmZsaWN0IGRldGVjdGlvbi4KCiMjIyB2MS40IOKAlCBBdXRvbm9tb3VzIFdvcmtmbG93cwpHb2FscywgcGxhbnMsIHBlcnNpc3RlbnQgcnVucywgYXBwcm92YWxzLCBjaGVja3BvaW50cywgcmV0cmllcywgcmVjb3ZlcnksIHdvcmtlciBjeWNsZXMsIG1vbml0b3JpbmcsIGRhc2hib2FyZCwgYW5kIG9wZXJhdGlvbmFsIHV0aWxpdGllcy4KCiMjIFBsYW5uZWQKCiMjIyB2MS41IOKAlCBLbm93bGVkZ2UgR3JhcGggYW5kIFJlYXNvbmluZwpFbnRpdHkgYW5kIHJlbGF0aW9uc2hpcCBzY2hlbWFzLCBwcm92ZW5hbmNlLCBleHRyYWN0aW9uLCBjb250cmFkaWN0aW9uIGRldGVjdGlvbiwgY2F1c2FsIGxpbmtzLCBkZWNpc2lvbiBzY29yaW5nLCBjb250ZXh0IHJhbmtpbmcsIGluZmVyZW5jZSByZWNvcmRzLCBncmFwaCBleHBsb3JlciwgY2VydGlmaWNhdGlvbiwgYW5kIGRhc2hib2FyZCBpbnRlZ3JhdGlvbi4KCiMjIyB2MS42IOKAlCBNdWx0aS1BZ2VudCBDb2xsYWJvcmF0aW9uClNwZWNpYWxpemVkIGFnZW50IGlkZW50aXRpZXMsIHJvbGVzLCBwZXJtaXNzaW9ucywgdGFzayBvd25lcnNoaXAsIHNoYXJlZCB3b3Jrc3BhY2VzLCBhZ2VudCBoYW5kb2ZmcywgZGViYXRlLCByZXZpZXcsIGNvbnNlbnN1cywgY29uZmxpY3QgcmVzb2x1dGlvbiwgcGFyYWxsZWwgZXhlY3V0aW9uLCBhbmQgYWdlbnQgbW9uaXRvcmluZy4KCiMjIyB2MS43IOKAlCBQZXJzb25hbCBGaW5hbmNpYWwgT2ZmaWNlCkFjY291bnRzLCBpbmNvbWUsIGV4cGVuc2VzLCBiaWxscywgZGVidCwgc2F2aW5ncyBnb2Fscywgc2lkZS1odXN0bGUgaW5jb21lLCBwYXljaGVjayBwbGFubmluZywgY2FzaC1mbG93IGZvcmVjYXN0cywgcHJvZml0YWJpbGl0eSBhbmFseXNpcywgcmVjb21tZW5kYXRpb25zLCBhbGVydHMsIGFuZCBmaW5hbmNpYWwgZGFzaGJvYXJkLgoKIyMjIHYxLjgg4oCUIEJ1c2luZXNzIEluY3ViYXRvcgpJZGVhIGNhcHR1cmUsIG9wcG9ydHVuaXR5IHNjb3JpbmcsIG1hcmtldCBhc3N1bXB0aW9ucywgcmVzZWFyY2gsIGNvbXBldGl0aXZlIGFuYWx5c2lzLCB2YWxpZGF0aW9uIGV4cGVyaW1lbnRzLCBsYXVuY2ggYnVkZ2V0cywgYnJhbmQgZGV2ZWxvcG1lbnQsIGNvbnRlbnQgcGlwZWxpbmVzLCByZXZlbnVlIHRlc3RzLCBhbmQgcGVyZm9ybWFuY2Ugc2NvcmVjYXJkcy4KCiMjIyB2Mi4wIOKAlCBBdXRvbm9tb3VzIEFJIEVudGVycHJpc2UKVW5pZmllZCBleGVjdXRpdmUgbW9kZWwsIGVudGVycHJpc2UgZ29hbHMsIGRlcGFydG1lbnQgYW5kIGFnZW50IGdvdmVybmFuY2UsIGNvbnRpbnVvdXMgb3BlcmF0aW5nIGN5Y2xlcywgY3Jvc3MtZGVwYXJ0bWVudCBvcmNoZXN0cmF0aW9uLCByZWN1cnJpbmcgbW9uaXRvcmluZywgbW9iaWxlIHRhc2sgY3JlYXRpb24sIERpc2NvcmQgY29tbWFuZCBhbmQgYXBwcm92YWwgaW50ZWdyYXRpb24sIGVudGVycHJpc2UgcmVwb3J0aW5nLCBhbmQgYSB1bmlmaWVkIGNvbnRyb2wgY2VudGVyLgoKIyMgUG9zdC12Mi4wIOKAlCBTZWxmLUhvc3RpbmcgQUkgT2ZmaWNlCkFJIE9mZmljZSBnZW5lcmF0ZXMsIHZhbGlkYXRlcywgdGVzdHMsIHBhY2thZ2VzLCBpbnN0YWxscywgZG9jdW1lbnRzLCBtb25pdG9ycywgYW5kIHJvbGxzIGJhY2sgaXRzIG93biBhcHByb3ZlZCB1cGdyYWRlcy4K"
Write-Base64File -RelativePath "PROJECT-STATUS.md" -Base64Content "IyBBSSBPZmZpY2UgUHJvamVjdCBTdGF0dXMKCiMjIEN1cnJlbnQgU3RhdHVzCgp8IEZpZWxkIHwgVmFsdWUgfAp8LS0tfC0tLXwKfCBDdXJyZW50IHBoYXNlIHwgUHJlcGFyaW5nIEtub3dsZWRnZSBHcmFwaCBhbmQgUmVhc29uaW5nIHwKfCBDdXJyZW50IG1pbGVzdG9uZSB8IENvcmUgQUkgT2ZmaWNlIFBsYXRmb3JtIENlcnRpZmllZCB8CnwgVmVyc2lvbiB8IDEuNC4wIHwKfCBPcGVyYXRpb25hbCBzdGF0ZSB8IE9wZXJhdGlvbmFsIHwKfCBEZXZlbG9wbWVudCBzdGF0ZSB8IFBhdXNlZCBmb3Igc2NoZWR1bGVkIHBlcnNvbmFsIGNvbW1pdG1lbnRzIHwKfCBSZXN1bWUgdGFyZ2V0IHwgdjEuNSBQYXJ0IEEg4oCUIEtub3dsZWRnZSBHcmFwaCBBcmNoaXRlY3R1cmUgfAoKIyMgQ29tcGxldGVkCgotIE9wZW5DbGF3IEdhdGV3YXkgcnVubmluZyBpbiBXU0wKLSBDZXJ0aWZpZWQgYXV0aGVudGljYXRlZCBPcGVuQ2xhdyBicmlkZ2UKLSBMaXZlIGV4ZWN1dGlvbiBhbmQgcmVzdWx0IHByb2Nlc3NpbmcKLSBDaGllZiBvZiBTdGFmZgotIERlcGFydG1lbnQgSW50ZWxsaWdlbmNlCi0gTG9uZy1UZXJtIE1lbW9yeQotIEF1dG9ub21vdXMgV29ya2Zsb3dzCi0gSHVtYW4gYXBwcm92YWwgZ2F0ZXMKLSBDaGVja3BvaW50IGFuZCByZWNvdmVyeSBzeXN0ZW0KLSBXb3JrZXIgcnVudGltZQotIE1vbml0b3JpbmcgYW5kIGV4ZWN1dGl2ZSByZXBvcnRzCi0gTG9jYWwgZGFzaGJvYXJkCi0gR2F0ZXdheSB0b2tlbiByb3RhdGlvbiB1dGlsaXR5CgojIyBSZXN1bWUgUG9pbnQKCkJlZ2luIEFJIE9mZmljZSB2MS41IFBhcnQgQS4KCiMjIFJlcXVpcmVkIEZ1dHVyZSBNb2JpbGUgSW50ZWdyYXRpb24KCkRpc2NvcmQgbXVzdCBiZWNvbWUgYSBtb2JpbGUgY29tbWFuZCwgdGFzayBjcmVhdGlvbiwgc3RhdHVzLCBhcHByb3ZhbCwgYW5kIG5vdGlmaWNhdGlvbiBjaGFubmVsLgo="
Write-Base64File -RelativePath "docs\RESUME-AI-OFFICE-DEVELOPMENT.md" -Base64Content "IyBSZXN1bWUgQUkgT2ZmaWNlIERldmVsb3BtZW50CgojIyBTdGFydGluZyBQb2ludAoKQUkgT2ZmaWNlIHYxLjQgaXMgb3BlcmF0aW9uYWwgYW5kIHRoZSBPcGVuQ2xhdyBicmlkZ2UgaXMgY2VydGlmaWVkLgoKVGhlIG5leHQgdGFzayBpczoKCmBgYHRleHQKQUkgT2ZmaWNlIHYxLjUgUGFydCBBIOKAlCBLbm93bGVkZ2UgR3JhcGggQXJjaGl0ZWN0dXJlCmBgYAoKIyMgRmlyc3QgU2Vzc2lvbiBCYWNrCgoxLiBDb25maXJtIHRoZSBHaXQgd29ya2luZyB0cmVlIGlzIGNsZWFuLgoyLiBDb25maXJtIHRhZyBgdjEuNC4wYCBleGlzdHMuCjMuIFN0YXJ0IGFuZCB2ZXJpZnkgdGhlIGRhc2hib2FyZC4KNC4gVmVyaWZ5IE9wZW5DbGF3IGF1dGhlbnRpY2F0aW9uLgo1LiBCZWdpbiBlbnRpdHksIHJlbGF0aW9uc2hpcCwgcHJvdmVuYW5jZSwgYW5kIGdyYXBoLWluZGV4IHNjaGVtYXMuCjYuIEFkZCB0aGUgZmlyc3Qga25vd2xlZGdlIGdyYXBoIHBhbmVsIHRvIHRoZSBkYXNoYm9hcmQuCgojIyBSZXF1aXJlZCBGdXR1cmUgSW50ZWdyYXRpb24KCkRpc2NvcmQgbXVzdCBiZWNvbWUgYSBtb2JpbGUgY29tbWFuZCwgdGFzayBjcmVhdGlvbiwgc3RhdHVzLCBhcHByb3ZhbCwgYW5kIG5vdGlmaWNhdGlvbiBjaGFubmVsLgo="
Write-Base64File -RelativePath "config\project-status.json" -Base64Content "ewogICJzY2hlbWFfdmVyc2lvbiI6ICIxLjAuMCIsCiAgInByb2R1Y3QiOiAiQUkgT2ZmaWNlIiwKICAidmVyc2lvbiI6ICIxLjQuMCIsCiAgImN1cnJlbnRfcGhhc2UiOiAiUHJlcGFyaW5nIEtub3dsZWRnZSBHcmFwaCBhbmQgUmVhc29uaW5nIiwKICAiY3VycmVudF9taWxlc3RvbmUiOiAiQ29yZSBBSSBPZmZpY2UgUGxhdGZvcm0gQ2VydGlmaWVkIiwKICAicmVsZWFzZV9zdGF0dXMiOiAib3BlcmF0aW9uYWwiLAogICJuZXh0X3JlbGVhc2UiOiAiMS41LjAiLAogICJuZXh0X21pbGVzdG9uZSI6ICJLbm93bGVkZ2UgR3JhcGggQXJjaGl0ZWN0dXJlIiwKICAicmVzdW1lX2NvbXBvbmVudCI6ICJ2MS41IFBhcnQgQSIsCiAgImRpc2NvcmRfaW50ZWdyYXRpb25fcGxhbm5lZCI6IHRydWUsCiAgInNlbGZfaG9zdGluZ19hZnRlciI6ICIyLjAuMCIKfQo="
Write-Base64File -RelativePath "scripts\utilities\Finalize-AIOfficeV14GitCheckpoint.ps1" -Base64Content "cGFyYW0oCiAgICBbc3dpdGNoXSRQdXNoCikKCiRFcnJvckFjdGlvblByZWZlcmVuY2UgPSAiU3RvcCIKCiRSb290ID0gKFJlc29sdmUtUGF0aCAoSm9pbi1QYXRoICRQU1NjcmlwdFJvb3QgIi4uXC4uIikpLlBhdGgKU2V0LUxvY2F0aW9uICRSb290CgppZiAoLW5vdCAoR2V0LUNvbW1hbmQgZ2l0IC1FcnJvckFjdGlvbiBTaWxlbnRseUNvbnRpbnVlKSkgewogICAgdGhyb3cgIkdpdCBpcyBub3QgaW5zdGFsbGVkIG9yIG5vdCBhdmFpbGFibGUgb24gUEFUSC4iCn0KCmdpdCBzdGF0dXMgLS1zaG9ydApnaXQgYWRkIC4KCiRQZW5kaW5nID0gZ2l0IHN0YXR1cyAtLXBvcmNlbGFpbgoKaWYgKFtzdHJpbmddOjpJc051bGxPcldoaXRlU3BhY2UoKCRQZW5kaW5nIHwgT3V0LVN0cmluZykpKSB7CiAgICBXcml0ZS1Ib3N0ICJObyBjaGFuZ2VzIHRvIGNvbW1pdC4iIC1Gb3JlZ3JvdW5kQ29sb3IgWWVsbG93Cn0KZWxzZSB7CiAgICBnaXQgY29tbWl0IC1tICJSZWxlYXNlIEFJIE9mZmljZSB2MS40IEF1dG9ub21vdXMgV29ya2Zsb3dzIgoKICAgIGlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7CiAgICAgICAgdGhyb3cgIkdpdCBjb21taXQgZmFpbGVkLiIKICAgIH0KfQoKJFRhZ0V4aXN0cyA9IGdpdCB0YWcgLS1saXN0ICJ2MS40LjAiCgppZiAoW3N0cmluZ106OklzTnVsbE9yV2hpdGVTcGFjZSgoJFRhZ0V4aXN0cyB8IE91dC1TdHJpbmcpKSkgewogICAgZ2l0IHRhZyAtYSB2MS40LjAgLW0gIkFJIE9mZmljZSB2MS40IEF1dG9ub21vdXMgV29ya2Zsb3dzIgoKICAgIGlmICgkTEFTVEVYSVRDT0RFIC1uZSAwKSB7CiAgICAgICAgdGhyb3cgIkdpdCB0YWcgY3JlYXRpb24gZmFpbGVkLiIKICAgIH0KCiAgICBXcml0ZS1Ib3N0ICJDcmVhdGVkIHRhZyB2MS40LjAuIiAtRm9yZWdyb3VuZENvbG9yIEdyZWVuCn0KZWxzZSB7CiAgICBXcml0ZS1Ib3N0ICJUYWcgdjEuNC4wIGFscmVhZHkgZXhpc3RzLiIgLUZvcmVncm91bmRDb2xvciBZZWxsb3cKfQoKaWYgKCRQdXNoKSB7CiAgICBnaXQgcHVzaCBvcmlnaW4gbWFpbiAtLXRhZ3MKCiAgICBpZiAoJExBU1RFWElUQ09ERSAtbmUgMCkgewogICAgICAgIHRocm93ICJHaXQgcHVzaCBmYWlsZWQuIgogICAgfQp9CgpnaXQgc3RhdHVzCldyaXRlLUhvc3QgIkFJIE9mZmljZSB2MS40IEdpdCBjaGVja3BvaW50IGNvbXBsZXRlLiIgLUZvcmVncm91bmRDb2xvciBHcmVlbgo="

$VersionPath = Join-Path $Repository "config\identity\version.json"

if (Test-Path -LiteralPath $VersionPath -PathType Leaf) {
    $Version = Get-Content -LiteralPath $VersionPath -Raw | ConvertFrom-Json
    $Version.version = "1.4.0"
    $Version.release_name = "Autonomous Workflows"
    $Version.status = "operational"
    $Version.installed_at = (Get-Date).ToString("o")
    $Version.next_planned_milestone = "1.5 Knowledge Graph and Reasoning"
    $Version | ConvertTo-Json -Depth 40 | Set-Content -LiteralPath $VersionPath -Encoding UTF8
    Write-Host "[UPDATED] config\identity\version.json" -ForegroundColor Green
}

$OfficePath = Join-Path $Repository "config\identity\office.json"

if (Test-Path -LiteralPath $OfficePath -PathType Leaf) {
    $Office = Get-Content -LiteralPath $OfficePath -Raw | ConvertFrom-Json
    $Office.version = "1.4.0"
    $Office.codename = "Autonomous Workflows"
    $Office.updated_at = (Get-Date).ToString("o")
    $Office | ConvertTo-Json -Depth 40 | Set-Content -LiteralPath $OfficePath -Encoding UTF8
    Write-Host "[UPDATED] config\identity\office.json" -ForegroundColor Green
}

$GitScriptPath = Join-Path $Repository "scripts\utilities\Finalize-AIOfficeV14GitCheckpoint.ps1"
$Tokens = $null
$ParseErrors = $null

[System.Management.Automation.Language.Parser]::ParseFile(
    $GitScriptPath,
    [ref]$Tokens,
    [ref]$ParseErrors
) | Out-Null

if ($ParseErrors.Count -gt 0) {
    throw ("Generated Git checkpoint script contains syntax errors: " + (($ParseErrors | ForEach-Object { $_.Message }) -join "; "))
}

Get-Content -LiteralPath (Join-Path $Repository "config\project-status.json") -Raw | ConvertFrom-Json | Out-Null

Write-Host ""
Write-Host "AI Office documentation updated to v1.4.0." -ForegroundColor Green
Write-Host "Backups: $BackupDirectory" -ForegroundColor Cyan
Write-Host ""
Write-Host "Review with:" -ForegroundColor Cyan
Write-Host "git diff -- README.md VISION.md ROADMAP.md PROJECT-STATUS.md"
Write-Host ""
Write-Host "Commit and tag with:" -ForegroundColor Cyan
Write-Host powershell -ExecutionPolicy Bypass -File ".\scripts\utilities\Finalize-AIOfficeV14GitCheckpoint.ps1"
Write-Host ""
Write-Host "Commit, tag, and push with:" -ForegroundColor Cyan
Write-Host powershell -ExecutionPolicy Bypass -File ".\scripts\utilities\Finalize-AIOfficeV14GitCheckpoint.ps1" -Push